# Generated by Django 4.0.3 on 2022-04-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import presents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='images/')),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('screenshot', models.ImageField(null=True, upload_to='images/')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('voters', models.IntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator_design', models.FloatField(default=0)),
                ('creator_usability', models.FloatField(default=0)),
                ('creator_creativity', models.FloatField(default=0)),
                ('creator_content', models.FloatField(default=0)),
                ('creator_score', models.FloatField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presents.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('design', presents.models.IntegerRangeField()),
                ('usability', presents.models.IntegerRangeField()),
                ('creativity', presents.models.IntegerRangeField()),
                ('content', presents.models.IntegerRangeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='presents.project')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presents.profile')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
