# Generated by Django 4.0.3 on 2022-04-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
