# Generated by Django 4.0.3 on 2022-04-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0002_remove_profile_link_remove_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='post_date',
        ),
    ]
